#!/bin/bash
read -p "Username: " username
read -p "Domain Name: " domain
WPDBNAME=`cat /home/${username}/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
WPDBUSER=`cat /home/${username}/public_html/wp-config.php | grep DB_USER | cut -d \' -f 4`
mysql -e "DROP DATABASE $WPDBNAME;"
mysql -e "DROP USER '${WPDBUSER}'@'localhost';"
rm /etc/php/7.2/fpm/pool.d/${username}.conf
rm /etc/nginx/sites-available/${domain}.conf
rm /etc/nginx/sites-enabled/${domain}.conf
rm -rf /home/$username
service php7.2-fpm stop
pkill -u $username
deluser $username
service php7.2-fpm start
service nginx restart


